#!/usr/bin/env python
from unittest import main, skip, TestCase
from assert_is import *
from osascript import osascript

class Test(TestCase):
    #@skip("")
    def test_osascript(self):
        eq_(osascript("return 1").strip(),"1")
        eq_(
            osascript("return {1,2,3}","h").strip().replace(" ","").split(","),
            ["1","2","3"]
        )

    #@skip("")
    @raises(Exception)
    def test_exception(self):
        osascript('display dialog "14/88"')

if __name__ == "__main__":
    main()