#!/usr/bin/env python
import sys
from osascript import osascript

if sys.platform == "darwin":  # linux,win32,cygwin,darwin
    returncode, stdout, stderr = osascript('return "message"')
    print(stdout)
